HOSTNAME: "fuel"
DNS_DOMAIN: "domain.tld"
DNS_SEARCH: "domain.tld"
DNS_UPSTREAM: "8.8.8.8"
NTP1: "0.fuel.pool.ntp.org"
NTP2: "1.fuel.pool.ntp.org"
NTP3: "2.fuel.pool.ntp.org"
FUEL_ACCESS:
  user: "admin"
  password: "admin"
BOOTSTRAP:
  flavor: "ubuntu"
  http_proxy: ""
  https_proxy: ""
  repos:
  - name: "ubuntu"
    section: "main universe multiverse"
    uri: "http://archive.ubuntu.com/ubuntu"
    priority: null
    suite: "trusty"
    type: "deb"
  - name: "ubuntu-updates"
    section: "main universe multiverse"
    uri: "http://archive.ubuntu.com/ubuntu"
    priority: null
    suite: "trusty-updates"
    type: "deb"
  - name: "ubuntu-security"
    section: "main universe multiverse"
    uri: "http://archive.ubuntu.com/ubuntu"
    priority: null
    suite: "trusty-security"
    type: "deb"
  - name: "mos"
    section: "main restricted"
    uri: "http://127.0.0.1:8080/ubuntu/x86_64"
    priority: 1050
    suite: "mos${mos_version}"
    type: "deb"
  - name: "mos-updates"
    section: "main restricted"
    uri: "http://mirror.fuel-infra.org/mos-repos/ubuntu/${mos_version}"
    priority: 1050
    suite: "mos${mos_version}-updates"
    type: "deb"
  - name: "mos-security"
    section: "main restricted"
    uri: "http://mirror.fuel-infra.org/mos-repos/ubuntu/${mos_version}"
    priority: 1050
    suite: "mos${mos_version}-security"
    type: "deb"
  - name: "mos-holdback"
    section: "main restricted"
    uri: "http://mirror.fuel-infra.org/mos-repos/ubuntu/${mos_version}"
    priority: 1100
    suite: "mos${mos_version}-holdback"
    type: "deb"
PRODUCTION: docker
FEATURE_GROUPS: []
